# Generated by Django 4.2.11 on 2024-04-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AMCProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("ac_no", models.CharField(max_length=255)),
                ("ifsc_code", models.CharField(max_length=255)),
                ("ac_name", models.CharField(max_length=255)),
                ("bank_name", models.CharField(max_length=255)),
                ("pan_no", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("pincode", models.CharField(max_length=255)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letter_no", models.CharField(max_length=255)),
                ("lab_name", models.CharField(max_length=255)),
                ("letter_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sr_no", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("buying_date", models.DateField()),
                ("department_name", models.CharField(max_length=255)),
                (
                    "letter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="letterCreation.letter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quotation_date", models.DateField()),
                ("ref_no", models.CharField(max_length=255)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="letterCreation.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subproduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_of_part", models.CharField(max_length=255)),
                ("part_name", models.CharField(max_length=255)),
                ("specification", models.TextField()),
                ("quantity", models.IntegerField()),
                ("period_of_amc_contract", models.CharField(max_length=255)),
                ("service_report_date", models.DateField()),
                (
                    "amc_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="letterCreation.amcprovider",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subproducts",
                        to="letterCreation.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuotationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "price_without_gst",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "price_with_gst",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("gst_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("gst_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expected_delivery", models.CharField(max_length=255)),
                (
                    "amc_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="letterCreation.amcprovider",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="letterCreation.quotation",
                    ),
                ),
                (
                    "subproduct",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="letterCreation.subproduct",
                    ),
                ),
            ],
        ),
    ]
