# Generated by Django 5.0.2 on 2024-06-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printtrack',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
