# Generated by Django 3.1.3 on 2024-06-19 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='product',
        ),
        migrations.AddField(
            model_name='printtrack',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='letter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='letterCreation.letter'),
        ),
    ]
