# Generated by Django 5.0.2 on 2024-06-28 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letterCreation.letter'),
        ),
    ]
