# Generated by Django 5.0.4 on 2024-06-17 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='product',
        ),
        migrations.AddField(
            model_name='printtrack',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='letter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='letterCreation.letter'),
        ),
    ]
