# Generated by Django 5.0.2 on 2024-04-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quotation_expense_criteria',
            field=models.CharField(choices=[('20%', '20%'), ('25%', '25%')], default='20%', max_length=3),
        ),
    ]
