# Generated by Django 3.1.3 on 2024-03-05 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0002_auto_20240302_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ac_no', models.CharField(max_length=255)),
                ('ifsc_code', models.CharField(max_length=255)),
                ('ac_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('pan_no', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ref_no', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letterCreation.product')),
            ],
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='period_of_amc_contract',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='SubproductQuotationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_without_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_with_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_delivery', models.CharField(max_length=255)),
                ('amc_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letterCreation.amcprovider')),
                ('quotation_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letterCreation.quotationinfo')),
                ('subproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letterCreation.subproduct')),
            ],
        ),
    ]
