# Generated by Django 5.0.4 on 2024-08-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0002_alter_quotation_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='unit_of_measure',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
