# Generated by Django 5.0.2 on 2024-06-16 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0002_printtrack_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='product',
        ),
        migrations.AddField(
            model_name='quotation',
            name='letter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='letterCreation.letter'),
        ),
    ]
