# Generated by Django 5.0.2 on 2024-04-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0002_quotation_quotation_expense_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
