# Generated by Django 3.1.3 on 2024-03-05 10:02

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0003_auto_20240305_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='department',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='subproduct',
            old_name='buying_date',
            new_name='service_report_date',
        ),
        migrations.RemoveField(
            model_name='subproduct',
            name='price_of_item',
        ),
        migrations.AddField(
            model_name='product',
            name='buying_date',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sr_no',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='letterCreation.letter'),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='period_of_amc_contract',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subproducts', to='letterCreation.product'),
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='specification',
            field=models.TextField(),
        ),
    ]
