# Generated by Django 5.0.2 on 2024-05-05 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0003_alter_mainitem_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainitem',
            name='manufacturer',
        ),
        migrations.CreateModel(
            name='MainItemManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letterCreation.mainitem')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letterCreation.manufacturer')),
            ],
        ),
    ]
