# Generated by Django 5.0.2 on 2024-05-05 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0005_mainitem_manufacturer_delete_mainitemmanufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainitem',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='letterCreation.manufacturer'),
        ),
    ]
