# Generated by Django 5.0.2 on 2024-05-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0006_alter_mainitem_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainitem',
            name='manufacturer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mainitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
