# Generated by Django 5.0.2 on 2024-05-05 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0007_alter_mainitem_manufacturer_alter_mainitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainitem',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letterCreation.manufacturer'),
        ),
    ]
