# Generated by Django 5.0.2 on 2024-03-10 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0007_alter_amcprovider_id_alter_letter_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationinfo',
            name='product',
        ),
        migrations.AddField(
            model_name='amcprovider',
            name='address',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amcprovider',
            name='pincode',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amcprovider',
            name='state',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationinfo',
            name='subproduct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='letterCreation.subproduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subproductquotationinfo',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subproductquotationinfo',
            name='gst_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subproductquotationinfo',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subproductquotationinfo',
            name='subproduct',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='letterCreation.subproduct'),
        ),
    ]
