# Generated by Django 5.0.2 on 2024-06-01 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0008_alter_mainitem_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReportTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reports', to='letterCreation.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='service_report_track',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='service_reports', to='letterCreation.servicereporttrack'),
            preserve_default=False,
        ),
    ]
