# Generated by Django 5.0.2 on 2024-03-10 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0008_remove_quotationinfo_product_amcprovider_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproductquotationinfo',
            name='amc_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='letterCreation.amcprovider'),
        ),
    ]
