# Generated by Django 5.0.2 on 2024-03-29 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0009_alter_subproductquotationinfo_amc_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproductquotationinfo',
            name='quotation_info',
        ),
        migrations.RemoveField(
            model_name='subproductquotationinfo',
            name='amc_provider',
        ),
        migrations.RemoveField(
            model_name='subproductquotationinfo',
            name='subproduct',
        ),
        migrations.AlterField(
            model_name='subproduct',
            name='amc_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letterCreation.amcprovider'),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_date', models.DateField()),
                ('ref_no', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letterCreation.product')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_without_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_with_gst', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gst_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_delivery', models.CharField(max_length=255)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letterCreation.quotation')),
                ('subproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letterCreation.subproduct')),
            ],
        ),
        migrations.DeleteModel(
            name='QuotationInfo',
        ),
        migrations.DeleteModel(
            name='SubproductQuotationInfo',
        ),
    ]
