# Generated by Django 5.0.2 on 2024-06-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0009_servicereporttrack_product_service_report_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='service_report_track',
        ),
        migrations.AlterField(
            model_name='product',
            name='service_report_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
