# Generated by Django 5.0.2 on 2024-03-29 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0010_remove_subproductquotationinfo_quotation_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='amc_provider',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='letterCreation.amcprovider'),
            preserve_default=False,
        ),
    ]
