# Generated by Django 5.0.2 on 2024-06-01 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0010_remove_product_service_report_track_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproduct',
            name='period_of_amc_contract',
        ),
    ]
