# Generated by Django 5.0.2 on 2024-06-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0011_remove_subproduct_period_of_amc_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='products',
            field=models.ManyToManyField(related_name='letters', to='letterCreation.product'),
        ),
    ]
