# Generated by Django 3.1.3 on 2024-06-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0011_remove_subproduct_period_of_amc_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereporttrack',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
