# Generated by Django 3.1.3 on 2024-03-30 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0011_quotationitem_amc_provider'),
        ('letterCreation', '0010_auto_20240310_1923'),
    ]

    operations = [
    ]
