# Generated by Django 5.0.2 on 2024-06-02 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0012_letter_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='products',
        ),
    ]
