# Generated by Django 5.0.2 on 2024-06-02 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0013_remove_letter_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letterCreation.letter')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letterCreation.product')),
            ],
        ),
    ]
