# Generated by Django 3.1.3 on 2024-06-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letterCreation', '0014_letterproduct'),
        ('letterCreation', '0012_auto_20240601_2010'),
    ]

    operations = [
    ]
