# Generated by Django 5.0.2 on 2024-02-17 06:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_department_lab_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='departments',
        ),
        migrations.AlterField(
            model_name='lab',
            name='address',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('warranty_period', models.IntegerField(help_text='in months')),
                ('warranty_type', models.CharField(choices=[('C', 'Comprehensive'), ('NC', 'Non-Comprehensive')], max_length=2)),
                ('warranty_provider', models.CharField(max_length=255)),
                ('ordered_date', models.DateField()),
                ('installation_date', models.DateField()),
                ('manufacturer', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.department')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.lab')),
            ],
        ),
    ]
