# Generated by Django 5.0.2 on 2024-02-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_remove_lab_departments_alter_lab_address_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='departments',
            field=models.ManyToManyField(related_name='labs', to='playground.department'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
