# Generated by Django 5.0.2 on 2024-02-17 07:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_lab_departments_alter_lab_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_to_replace', models.CharField(max_length=255)),
                ('specification', models.TextField()),
                ('price_without_gst', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quotation_status', models.CharField(choices=[('A', 'Approved'), ('NA', 'Not Approved')], max_length=2)),
                ('quotation_from_company_status', models.CharField(choices=[('R', 'Received'), ('NR', 'Not Received')], max_length=2)),
                ('price_with_gst', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.order')),
            ],
        ),
    ]
