# Generated by Django 5.0.2 on 2024-02-17 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_warrantyclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyclaim',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_claim', to='playground.order'),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='price_with_gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='quotation_from_company_status',
            field=models.CharField(choices=[('received', 'Received'), ('not_received', 'Not Received')], max_length=20),
        ),
        migrations.AlterField(
            model_name='warrantyclaim',
            name='quotation_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('not_approved', 'Not Approved')], max_length=20),
        ),
    ]
