# Generated by Django 5.0.2 on 2024-02-17 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_alter_warrantyclaim_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyclaim',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.order'),
        ),
    ]
