# Generated by Django 5.0.2 on 2024-02-20 14:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_alter_warrantyclaim_price_with_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='lab',
            name='address',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='lab_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='installation_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='model',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='warranty_period',
        ),
        migrations.RemoveField(
            model_name='order',
            name='warranty_provider',
        ),
        migrations.RemoveField(
            model_name='order',
            name='warranty_type',
        ),
        migrations.AddField(
            model_name='department',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='playground.lab'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'lab')},
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('warranty_period', models.IntegerField(help_text='in months')),
                ('warranty_type', models.CharField(choices=[('C', 'Comprehensive'), ('NC', 'Non-Comprehensive')], max_length=2)),
                ('warranty_provider', models.CharField(max_length=255)),
                ('ordered_date', models.DateField()),
                ('installation_date', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.department')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.lab')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_frequency', models.CharField(choices=[('yearly', 'Yearly'), ('half-yearly', 'Half-Yearly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('visit_date', models.DateField()),
                ('submitted', models.BooleanField(default=False)),
                ('upload', models.FileField(blank=True, null=True, upload_to='service_reports/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.item')),
            ],
        ),
    ]
