# Generated by Django 5.0.2 on 2024-02-20 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_manufacturer_remove_lab_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_quantity',
        ),
        migrations.AlterField(
            model_name='department',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.lab'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='playground.order')),
            ],
        ),
    ]
