# Generated by Django 5.0.2 on 2024-02-21 13:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_remove_order_total_quantity_alter_department_lab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMC_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='warrantyclaim',
            name='order',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='warranty_type',
            new_name='AMC_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='department',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lab',
        ),
        migrations.AddField(
            model_name='item',
            name='item_code',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='serial_code',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='address',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='playground.OrderItem', to='playground.item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.order'),
        ),
        migrations.CreateModel(
            name='AMC_Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_to_replace', models.CharField(max_length=255)),
                ('specification', models.TextField()),
                ('price_without_gst', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quotation_status', models.CharField(choices=[('approved', 'Approved'), ('not_approved', 'Not Approved')], max_length=20)),
                ('quotation_from_company_status', models.CharField(choices=[('received', 'Received'), ('not_received', 'Not Received')], max_length=20)),
                ('price_with_gst', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quotation_letter_no', models.CharField(blank=True, max_length=100, null=True)),
                ('quotation_letter_date', models.DateField(blank=True, null=True)),
                ('received_quotation_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bank_details', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.order')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='playground.category'),
        ),
        migrations.DeleteModel(
            name='ServiceReport',
        ),
        migrations.DeleteModel(
            name='WarrantyClaim',
        ),
    ]
