# Generated by Django 5.0.2 on 2024-02-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_amc_provider_category_remove_warrantyclaim_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
    ]
