# Generated by Django 5.0.2 on 2024-02-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_alter_manufacturer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='department',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lab',
        ),
        migrations.AddField(
            model_name='item',
            name='AMC_exist',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='AMC_type',
            field=models.CharField(blank=True, choices=[('C', 'Comprehensive'), ('NC', 'Non-Comprehensive')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='warranty_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
