# Generated by Django 5.0.2 on 2024-02-21 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0014_amc_provider_account_no_amc_provider_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='AMC_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.amc_provider'),
        ),
        migrations.AddField(
            model_name='item',
            name='Warranty_type',
            field=models.CharField(blank=True, choices=[('C', 'Comprehensive'), ('NC', 'Non-Comprehensive')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='warranty_exist',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
