# Generated by Django 5.0.2 on 2024-02-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0016_orderitem_amc_exist_orderitem_amc_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='AMC_provider',
        ),
        migrations.RemoveField(
            model_name='item',
            name='AMC_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='Warranty_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='warranty_provider',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AlterField(
            model_name='item',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
