# Generated by Django 5.0.2 on 2024-02-21 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0017_remove_item_amc_provider_remove_item_amc_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='AMC_exist',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='AMC_provider',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='AMC_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='Warranty_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='warranty_exist',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='warranty_provider',
        ),
        migrations.AddField(
            model_name='item',
            name='AMC_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.amc_provider'),
        ),
        migrations.AddField(
            model_name='item',
            name='AMC_type',
            field=models.CharField(blank=True, choices=[('C', 'Comprehensive'), ('NC', 'Non-Comprehensive')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Warranty_type',
            field=models.CharField(blank=True, choices=[('C', 'Comprehensive'), ('NC', 'Non-Comprehensive')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='warranty_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='playground.OrderItem', to='playground.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='installation_date',
            field=models.DateField(),
        ),
    ]
